# Crie um programa que leia algo pelo teclado e mostre na tela alguma informação sobre ele.
print('====Exercício Aula 06====')
valor1  = input('Digite algo (isnumeric): ')
print(valor1.isnumeric())
valor1  = input('Digite algo (isalpha): ')
print(valor1.isalpha())
valor1  = input('Digite algo (isalnum): ')
print(valor1.isalnum())
valor1  = input('Digite algo (isupper): ')
print(valor1.isupper())
valor1  = input('Digite algo (islower): ')
print(valor1.islower())
valor1  = input('Digite algo (isprintable): ')
print(valor1.isprintable())
valor1  = input('Digite algo (isspace): ')
print(valor1.isspace())
