print('====Desafio 02 - Aula 04====')
dia = input('Dia de nascimento: ')
mes = input('Mês de nascimento: ')
ano = input('Ano de nascimento: ')
print('---------------------------')
print('Você nasceu em',dia,'de',mes,'de',ano,'! Correto?')
